#### THIS FILE IS MANAGED BY AN AUTOMATED WORKFLOW ####

# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

exclude: '(^themes.*|^static/files/.*)'
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: check-yaml
        files: \.yaml$, \.yml$
        types: [file]
      - id: check-case-conflict
      - id: check-json
        files: \.json$
        types: [file]
      - id: check-symlinks
      - id: check-toml
        files: \.toml$
        types: [file]
      - id: check-xml
        files: \.xml$
        types: [file]
      - id: check-merge-conflict
      - id: mixed-line-ending
        args: [ --fix=no ]
      - id: pretty-format-json
        files: '!htmltest_output/refcache.json$'

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.26.0
    hooks:
      - id: eslint
        files: \.[jt]sx?$ # *.js, *.jsx, *.ts and *.tsx
        types: [file]
        additional_dependencies:
          - eslint-config-prettier@8.5.0
          - eslint-plugin-deprecation@1.3.2
          - eslint-plugin-import@2.26.0
          - eslint-plugin-unused-imports@2.0.0

  - repo: https://github.com/syntaqx/git-hooks
    rev: v0.0.17
    hooks:
      - id: shellcheck
        files: \.sh$
        types: [file]
      - id: shfmt
        files: \.sh$
        types: [file]
