#!/bin/bash

failed_items=""
function install_package() {
echo EXECUTING: brew install $1 $2
brew install $1 $2
[ $? -ne 0 ] && $failed_items="$failed_items $1"  # package failed to install.
}
brew tap caskroom/cask
brew tap caskroom/versions
brew tap homebrew/binary
brew tap homebrew/completions
brew tap homebrew/fuse
brew tap homebrew/php
brew tap homebrew/science
brew tap homebrew/versions
brew tap jimbojsb/launchrocket
brew tap jingweno/ccat
brew tap josegonzalez/php
brew tap nwoolls/xgminer
brew tap petere/postgresql
brew tap ravenac95/sudolikeaboss
install_package ansible ''
install_package arpack ''
install_package arping ''
install_package asciidoc ''
install_package aspell ''
install_package atk ''
install_package autoconf ''
install_package automake ''
install_package axel ''
install_package bash ''
install_package bazaar ''
install_package bfg ''
install_package brew-cask ''
install_package c-ares ''
install_package cabal-install ''
install_package cabextract ''
install_package cairo ''
install_package ccat ''
install_package cloog ''
install_package cloog-ppl015 ''
install_package cmake ''
install_package colordiff ''
install_package coreutils ''
install_package cpanminus ''
install_package curl ''
install_package d-bus ''
install_package dadadodo ''
install_package dialog ''
install_package distribution ''
install_package docbook ''
install_package docker ''
install_package docker-machine ''
install_package dos2unix ''
install_package enchant ''
install_package epstool ''
install_package exercism ''
install_package faac ''
install_package fftw ''
install_package fontconfig '  --universal'
install_package fpp ''
install_package freetype '  --universal'
install_package gawk ''
install_package gcc ''
install_package gd '  --universal'
install_package gdbm ''
install_package gdk-pixbuf ''
install_package gem-completion ''
install_package geoip ''
install_package gettext ''
install_package ghc ''
install_package ghostscript ''
install_package git ''
install_package gl2ps ''
install_package glew ''
install_package glib ''
install_package glm ''
install_package glpk ''
install_package gmp ''
install_package gmp4 ''
install_package gnu-sed ''
install_package gnu-tar ''
install_package gnupg ''
install_package gnutls ''
install_package go ''
install_package gobject-introspection ''
install_package graphicsmagick ''
install_package graphviz ''
install_package gtk+ ''
install_package harfbuzz ''
install_package hdf5 ''
install_package hicolor-icon-theme ''
install_package hidapi ''
install_package htop-osx ''
install_package httrack ''
install_package icu4c ''
install_package iftop ''
install_package imagemagick ''
install_package intltool ''
install_package isl ''
install_package jansson ''
install_package jasper '  --universal'
install_package jbig2dec ''
install_package jpeg '  --universal'
install_package jshon ''
install_package keybase ''
install_package lame ''
install_package libav ''
install_package libdvdcss ''
install_package libevent ''
install_package libffi ''
install_package libgcrypt ''
install_package libgpg-error ''
install_package libgphoto2 '  --universal'
install_package libicns '  --universal'
install_package libksba ''
install_package libmicrohttpd ''
install_package libmpc ''
install_package libmpc08 ''
install_package libnet ''
install_package libpng '  --universal'
install_package libtasn1 ''
install_package libtiff '  --universal'
install_package libtool '  --universal'
install_package libusb '  --universal'
install_package libusb-compat '  --universal'
install_package libyaml ''
install_package little-cms2 '  --universal'
install_package lua ''
install_package luajit ''
install_package lynis ''
install_package makedepend ''
install_package mercurial ''
install_package mobile-shell ''
install_package mono ''
install_package mpfr ''
install_package mpfr2 ''
install_package mtr ''
install_package ncdu ''
install_package nettle ''
install_package nmap ''
install_package node ''
install_package openconnect ''
install_package openssl '  --universal'
install_package ossp-uuid ''
install_package p11-kit ''
install_package p7zip ''
install_package packer-completion ''
install_package pandoc ''
install_package pango ''
install_package parallel ''
install_package pcre ''
install_package peco ''
install_package perf ''
install_package pgbadger ''
install_package pgcli ''
install_package pixman ''
install_package pkg-config ''
install_package platypus ''
install_package plotutils ''
install_package postgresql ''
install_package ppl011 ''
install_package protobuf ''
install_package psqlodbc ''
install_package pstoedit ''
install_package py2cairo ''
install_package pygobject ''
install_package pygtk ''
install_package pyqt ''
install_package qhull ''
install_package qrupdate ''
install_package qscintilla2 ''
install_package qt ''
install_package rake-completion ''
install_package readline ''
install_package ruby-completion ''
install_package sane-backends '  --universal'
install_package shellcheck ''
install_package siege ''
install_package sip ''
install_package sqlite ''
install_package sshfs ''
install_package sudolikeaboss ''
install_package sudolikeaboss-workaround ''
install_package suite-sparse ''
install_package sysdig ''
install_package szip ''
install_package tbb ''
install_package texi2html ''
install_package tig ''
install_package tmux ''
install_package tmux-cssh ''
install_package toggle-osx-shadows ''
install_package unixodbc ''
install_package unrar ''
install_package uthash ''
install_package vbindiff ''
install_package veclibfort ''
install_package vpnc ''
install_package wget ''
install_package wine ''
install_package wireshark '  --with-qt'
install_package x264 ''
install_package xvid ''
install_package xz ''
install_package yasm ''
install_package youtube-dl ''
install_package zsh ''
[ ! -z $failed_items ] && echo The following items were failed to install: && echo $failed_items
