#### THIS FILE IS MANAGED BY AN AUTOMATED WORKFLOW ####

name: "🤔 Question / Something else"
description: Create a new ticket for something that's not a bug or feature
title: "💭 <title>"
labels: ["question"]
body:
  - type: textarea
    id: question
    attributes:
      label: "Details"
      description: Details
    validations:
      required: false
