#!/usr/bin/env bash
set -euo pipefail

cd /Users/samm/git/llama.cpp

# Pull latest unless we're on main/master (where we don't want to auto-update).
branch=$(git rev-parse --abbrev-ref HEAD)
if [ "$branch" = "main" ] || [ "$branch" = "master" ]; then
    echo "On $branch, skipping pull."
else
    echo "On branch '$branch', pulling latest changes..."
    git pull
fi

# Wipe untracked cruft. Respects .gitignore, so build.sh, CMakeUserPresets.json,
# and ccache (outside the repo) all survive. This catches legacy in-tree cmake
# artefacts (top-level Makefile, autogenerated/, bin/, examples/CMakeFiles/, ...)
# and the stale build-info.h at the repo root, which would otherwise shadow
# common/build-info.h and break the build.
git clean -fd

# Force a fresh configure. CMakeCache.txt goes stale whenever Homebrew bumps a
# dep (e.g. openssl@3 path version changes) and cmake won't always notice on its
# own. ccache (~/Library/Caches/ccache) is unaffected, so this stays cheap.
rm -rf build

cmake --preset local
cmake --build build --parallel 12
cmake --install build
