#### THIS FILE IS MANAGED BY AN AUTOMATED WORKFLOW ####

name: "Sync Available Github Labels"

on:
  workflow_dispatch:
  schedule:
    - cron: "30 4 * * 0"
  push:
    paths:
      - .github/config/labels.yml
      - .github/config/labeller.yml
      - .github/workflows/label-sync.yml

permissions:
  pull-requests: write
  contents: read
  issues: write

# One build per branch, cancel out of date builds
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  sync-labels:
    name: Sync Github Labels
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3
      - uses: EndBug/label-sync@da00f2c11fdb78e4fae44adac2fdd713778ea3e8 # v2
        with:
          delete-other-labels: true
          dry-run: false
          token: ${{ secrets.GITHUB_TOKEN }}
          config-file: .github/config/labels.yml
