#### THIS FILE IS MANAGED BY AN AUTOMATED WORKFLOW ####

name: "Sync Available Github Labels"

on:
  workflow_dispatch:
  schedule:
    - cron: "30 4 * * *"

permissions:
  pull-requests: write
  contents: read
  issues: write

# One build per branch, cancel out of date builds
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  sync-labels:
    name: Sync Github Labels
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # tag=v3
      - uses: EndBug/label-sync@34787058c3498a674f22425940797579f4bd89f2 # tag=v2
        with:
          delete-other-labels: true
          dry-run: false
          token: ${{ secrets.GITHUB_TOKEN }}
          config-file: .github/config/labels.yml
