#### THIS FILE IS MANAGED BY AN AUTOMATED WORKFLOW ####

name: "Lint Github Actions Workflows"
on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize
    branches:
      - main
      - master
      - "!repo-sync/**"
      - "!renovate/**"
      - "!update/pre-commit-hooks/**"
    paths:
      - ".github/**"
      - "!**/node_modules/**"

permissions:
  contents: read
  checks: write
  pull-requests: write
  issues: write
  statuses: write
  actions: read

# One build per branch, cancel out of date builds
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint-actions-workflows:
    name: Lint Actions Workflows
    runs-on: ubuntu-22.04
    if: ${{ !github.event.pull_request.draft }}
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # tag=v3
      - uses: reviewdog/action-actionlint@5c714fa8ca7b5ea8d929d273ed5bb2e3a4a7c019 # v1
        with:
          actionlint_flags: -ignore 'SC2086' -ignore 'SC2129'
          fail_on_error: false
          level: error
          reporter: github-pr-review
          filter_mode: file
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
