#### THIS FILE IS MANAGED BY AN AUTOMATED WORKFLOW ####

name: Lint Markdown Files

# https://github.com/reviewdog/action-markdownlint

on:
  pull_request:
    paths:
      - "*.md"
      - "pages/**/*.md"
      - "posts/**/*.md"
      - "_pages/**/*.md"
      - "_posts/**/*.md"
      - "docs/**/*.md"
      - "documentation/**/*.md"
      - "!**/node_modules/**"
    branches:
      - main
      - master
      - "!repo-sync/**"
      - "!renovate/**"
      - "!update/pre-commit-hooks/**"
  workflow_dispatch:

permissions:
  contents: read
  checks: write
  pull-requests: write

# One build per branch, cancel out of date builds
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint-markdown:
    name: Lint Markdown
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3
      - name: markdownlint
        uses: reviewdog/action-markdownlint@97e3df02fe1573d505a7b268046a44fa5409cbc3 # tag=v0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          level: error
          filter_mode: added
          fail_on_error: false
          markdownlint_flags: "'**/*.md' --ignore node_modules --disable MD013"
