#### THIS FILE IS MANAGED BY AN AUTOMATED WORKFLOW ####

name: "Lint CODEOWNERS"
on:
  pull_request:
    paths:
      - "**/CODEOWNERS"
      - "!**/node_modules/**"
    branches:
      - main
      - master

# One build per branch, cancel out of date builds
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  issues: write
  pull-requests: write
  statuses: write
  checks: write
  contents: read
  security-events: read

jobs:
  lint-codeowners:
    name: "Lint CODEOWNERS file"
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # tag=v3
      - uses: mszostok/codeowners-validator@7f3f5e28c6d7b8dfae5731e54ce2272ca384592f # tag=v0.7.4
        with:
          checks: "files,duppatterns,syntax"
          experimental_checks: "avoid-shadowing"
          github_access_token: "${{ secrets.GITHUB_TOKEN }}"
