#### THIS FILE IS MANAGED BY AN AUTOMATED WORKFLOW ####

name: Mirror repo to GitLab

on:
  push:
  delete:
  workflow_dispatch:

permissions:
  contents: read
  actions: read

# One build per branch, cancel out of date builds
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  to_gitlab:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url: git@gitlab.com:${{ github.repository }}-mirror.git
          ssh_private_key: ${{ secrets.GITLAB_SSH_PRIVATE_KEY }}
