#### THIS FILE IS MANAGED BY AN AUTOMATED WORKFLOW ####

name: "Pull Request Labeller"
on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize
      - ready_for_review
    branches:
      - main
      - master

# One build per branch, cancel out of date builds
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  issues: write
  pull-requests: write
  statuses: write
  checks: write
  contents: read
  security-events: read

jobs:
  pr-labeller:
    name: "Pull Request Labeller"
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    steps:
      - uses: fuxingloh/multi-labeler@f5bd7323b53b0833c1e4ed8d7b797ae995ef75b4 # tag=v2
        id: pr-labeller
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          config-path: .github/config/labeller.yml
