#### THIS FILE IS MANAGED BY AN AUTOMATED WORKFLOW ####

name: "Check for TODOs and create or update issues"

on:
  workflow_dispatch:
  schedule:
    - cron: "0 15 * * 6"

permissions:
  issues: write
  contents: read
  actions: read

# One build per branch, cancel out of date builds
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  todo-issues:
    runs-on: "ubuntu-latest"
    timeout-minutes: 15
    steps:
      - uses: "actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab" # v3
      - name: "Check for TODOs and create or update issues"
        uses: ribtoks/tdg-github-action@master
        with:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
          SHA: ${{ github.sha }}
          REF: ${{ github.ref }}
          EXCLUDE_PATTERN: "(node_modules|dist|bin|files|assets|i18n|themes)/.*"
          MIN_WORDS: 2
          MIN_CHARACTERS: 10
          ADD_LIMIT: 10
          COMMENT_ON_ISSUES: true
